### ISSUE TITLE
intersecting a box with a cone results in a slice of the surface of the cone instead of a solid object

### ISSUE THREAD

**Issue by steveliles** [manthrax/THREE-CSGMesh#10]
When intersecting a BoxBufferGeom with a ConeBufferGeom I don't end up with a solid object, i get a slice of the surface of the cone. I imagine I'm doing something wrong, but i can't for the life of me figure it out.

I started from the two BoxGeom's example in the README (which worked!) then modified them to be different shapes. I am using react-three-fiber but the CSG stuff is separate and deals only with normal three objects.

Equally puzzling, box.subtract(cone) gives the same exact result as intersect (slice of the surface of the cone).

![cone-box-intersection-manthrax](https://user-images.githubusercontent.com/441745/115312343-11f77480-a169-11eb-98e6-d6f141c9f7c0.gif)

* cone.subtract(box) gives the inverse of intersect - a hollow cone with a slice of its surface missing.
* box.union(cone) gives the same exact result as cone.subtract(box)! 

![cone-box-union-manthrax](https://user-images.githubusercontent.com/441745/115312643-977b2480-a169-11eb-83ef-bd7d211667a4.gif)

demo code: https://codesandbox.io/s/manthrax-shapes-hollow-bsqij?file=/src/App.js

FWIW, I've been trying out a bunch of three CSG libs and having issues with pointy objects like cones in all of them. The common denominator here appears to be me, but I just can't understand where i've gone wrong?

**Comment by darkwave** [comment]
I'm using plain three.js (ver `0.127.0`) and I'm having the same issue with cones.

I noticed that:
1. Changing order of meshes doesn't change the result in union operation
2. The resulting mesh has some faces with _inverted normals_

**Comment by darkwave** [comment]
@steveliles just found a temporary workaround: Instead of using a [ConeGeometry](https://threejs.org/docs/index.html?q=cone#api/en/geometries/ConeGeometry) you may use a [CylinderGeometry](https://threejs.org/docs/index.html?q=cone#api/en/geometries/CylinderGeometry) with a very small `radiusTop` :sweat_smile:

@manthrax Using `radiusTop` equals to 0 (resulting in a _perfect_ cone) present the same issue. I hope this is an hint of what is happening :crossed_fingers:

**Comment by manthrax** [comment]
@darkwave This should be fixed in the latest release. The problem was that the ConeGeometry creates some faces that have 3 identical vertices, (1 point).. faces with no area don't have a surface normal, so the conversion to BSP was breaking.
We've added a check to filter out invalid BSP planes, and that seems to fix this issue.

Can you verify if this still occurs with the latest build? Thanks for the hints! :D

**Comment by giladdarshan** [comment]
Hey @manthrax, I still see this issue with the latest versions of three.js and THREE-CSGMesh.

I saw the fix in the referenced issue, and can confirm it works with a slight modification.
Change [Line #73](https://github.com/manthrax/THREE-CSGMesh/blob/master/three-csg.js#L73)
From:
```return CSG.fromPolygons(polys)```
To:
```return CSG.fromPolygons(polys.filter(p=>!isNaN(p.plane.normal.x)));```
